### ISSUE TITLE
Remove shaking of background image on mouse hover

### ISSUE THREAD

**Issue by prateek76** [GeekHaven/Aparoksha-19#15]

**Comment by neerajd007** [comment]
@opencodebot claim

**Comment by prateek76** [comment]
> @opencodebot claim

Go ahead

**Comment by neerajd007** [comment]
@prateek76  Please! guide me to the correct file in where I can find the CSS of background image.

**Comment by prateek76** [comment]
@neerajd007 live link

**Comment by neerajd007** [comment]
Here is the live link: https://neerajd007.github.io/Aparoksha-19/
